export const METADATA = {
  author: "KMaar",
  title: "Abhisehk Kumar | KMaar",
  description:
    "Explore the portfolio of Abhishek Kumar, a Full Stack Developer skilled in JavaScript, React, Node.js, and Next.js. Discover innovative projects, frontend and backend expertise, and valuable insights in web development.",
  siteUrl: "https://www.kmaar.vercel.app/",
  twitterHandle: "@kmaar44",
  keywords: [
    "Abhishek Kumar",
    "Agile Development",
    "API Development",
    "Backend Programming",
    "Backend Scalability",
    "Backend Security",
    "Blogging Platforms",
    "Clean Code",
    "Code Documentation",
    "Code Optimization",
    "Code Refactoring",
    "Continuous Delivery",
    "Continuous Integration (CI)",
    "Conversion Rate Optimization (CRO)",
    "Creative Developer",
    "CSS Preprocessors",
    "Database Management",
    "Debugging",
    "Design Patterns",
    "Digital Portfolio",
    "E-commerce Development",
    "Express.js",
    "Frontend Components",
    "Frontend Developer",
    "Frontend Frameworks",
    "Frontend Performance",
    "Full Stack Developer",
    "GraphQL",
    "Headless CMS",
    "HTML/CSS",
    "Interaction Design",
    "JavaScript",
    "JavaScript Frameworks",
    "KMaar",
    "Landing Page Optimization",
    "Microservices",
    "Mobile-Friendly Design",
    "Node.js",
    "Object-Oriented Programming (OOP)",
    "Online Identity",
    "Online Portfolio",
    "Online Presence",
    "Personal Branding",
    "Personal Website",
    "Portfolio",
    "Portfolio Presentation",
    "Portfolio Showcase",
    "Problem-Solving",
    "Progressive Web Apps (PWAs)",
    "React",
    "Responsive Design",
    "Responsive Web Design",
    "RESTful APIs",
    "Search Engine Optimization (SEO)",
    "Server-side Development",
    "Serverless Architecture",
    "Showcase Website",
    "Single-Page Applications (SPAs)",
    "Software Architecture",
    "Software Developer",
    "Software Development Life Cycle (SDLC)",
    "Software Engineer",
    "Software Quality Assurance",
    "State Management",
    "Static Site Generation (SSG)",
    "Tech Enthusiast",
    "Technology Showcase",
    "Test-Driven Development (TDD)",
    "TypeScript",
    "UI Libraries",
    "UI/UX Design",
    "Unit Testing",
    "User Experience",
    "User Interface",
    "Version Control Best Practices",
    "Web Analytics",
    "Web Applications",
    "Web Design",
    "Web Development",
  ].join(", "),
  image: "https://kmaar.vercel.app",
  language: "English",
};

export const GTAG = "GTM-5BNX69TM";
